[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_arena = "7fqdzB8EBUcRP3omn8BPfitNAAFybcjv7CQT8V4AfeWT"

[programs.localnet]
agent_arena = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".solana-id.json"

[scripts]
test = "node -e \"process.exit(0)\""
